# Não é necessário Docker para MongoDB Atlas
# Apenas o container da aplicação
version: '3.8'

services:
  yup-api:
    build: .
    container_name: yup_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://plablo:<db_password>@ac-zgmviop-shard-00-00.t0ozb1f.mongodb.net:27017,ac-zgmviop-shard-00-01.t0ozb1f.mongodb.net:27017,ac-zgmviop-shard-00-02.t0ozb1f.mongodb.net:27017/?ssl=true&replicaSet=atlas-y77oa6-shard-0&authSource=admin&appName=Cluster0
      - MONGODB_DB_NAME=yup_customer_service
      - ZAPI_INSTANCE_ID=3F43467A7F5BF175DDAF66DA177DAE5D
      - ZAPI_TOKEN=7B297D6399C13767601B1C78
      - ZAPI_URL=https://api.z-api.io
    env_file:
      - .env
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload